name: Application - Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      GOPATH: ~

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v -race ./test/...

#      - name: Build
#        run: go build -v ./...
#
#      - name: GoFmt Check
#        run: gofmt -s -w ./
#
#      - name: Run go vet
#        run: go vet ./...
#
#      - name: Run staticcheck
#        run: |
#          export PATH=${PATH}:`go env GOPATH`/bin
#          go get -u honnef.co/go/tools/cmd/staticcheck
#          staticcheck ./...
