name: Application - Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      GOPATH: ~

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Copy into GOPATH
        run: |
          mkdir $HOME/src/go-tree-demo
          cp -r ../go-tree-demo $HOME/src/go-tree-demo

      - name: LS Check
        run: ls -a $HOME/src/go-tree-demo

      - name: Build
        run: go build -v ./...

      - name: GoFmt Check
        run: gofmt -s -w ./

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Run tests
        run: go test -race -vet=off ./test/...
