name: Application - Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ "windows-latest", "ubuntu-latest", "macOS-latest" ]
        go: [ "1.19", "1.20"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -race ./test/...

      - name: GoFmt Check
        run: gofmt -s -w ./

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          cache-key: ${{ matrix.go }}
