name: Application - Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install Lint Dependencies
        run: |
          go install golang.org/x/lint/golint@latest 
          go install honnef.co/go/tools/cmd/staticcheck@latest
        env:
          GOPATH: $HOME

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: GoFmt Check
        run: gofmt -s -w ./

      - name: Run go vet
        run: go vet ./...


      - name: Run golint
        run: golint ./...
        env:
          GOPATH: $HOME

      - name: Run staticcheck
        run: staticcheck ./...
        env:
          GOPATH: $HOME

      - name: Run tests
        run: go test -race -vet=off ./...
